### ISSUE TITLE
Mapping Issue

### ISSUE THREAD

**Issue by jeezany** [Fribb/anime-lists#15]
Anime name is Senran Kagura Shinovi Master: Tokyo Youma-hen.

My filesystem folder name is "Senran Kagura Shinovi Master - Tokyo Youma-hen [mal-36037]" which would auto map it to the anime in MAL.

The Issue is that the Thumbnail will point to season one in thetvdb. I tried to move the media to "Season 2" folder to see if it will take the meta of season 2

What is the proper way to work around this issue?
Is there a way for me to pick anidb or anilist for the metadatas?

 {
    "livechart_id": 893,
    "thetvdb_id": 264053,
    "anime-planet_id": "senran-kagura",
    "anisearch_id": 7795,
    "anidb_id": 9166,
    "kitsu_id": 7216,
    "mal_id": 15119,
    "type": "TV",
    "notify.moe_id": "umEOtKiig",
    "anilist_id": 15119
  },
  {
    "livechart_id": 1263,
    "thetvdb_id": 264053,
    "anime-planet_id": "senran-kagura-estival-versus-shoujo-tachi-no-sentaku",
    "anisearch_id": 10030,
    "anidb_id": 10885,
    "kitsu_id": 10005,
    "mal_id": 27967,
    "type": "OVA",
    "notify.moe_id": "ZDsPtFiiR",
    "anilist_id": 21129
  },
  {
    "livechart_id": 2819,
    "thetvdb_id": 264053,
    "anime-planet_id": "senran-kagura-shinovi-master",
    "anisearch_id": 12682,
    "anidb_id": 13341,
    "kitsu_id": 13690,
    "mal_id": 36037,
    "type": "TV",
    "notify.moe_id": "Bh_V2Kimg",
    "anilist_id": 102822
  },

Thank you for your work.

**Comment by Fribb** [comment]
I think you are more talking about the MyAnimeList Metadata rather than a mapping issue?! Because the mapping seems to be correct.

I think the reason for your confusion is because of the difference in how those websites organize their releases.

For example, MyAnimeList has every release with its own ID while TheTVDB or TheMovieDB can have different releases as one series (organized in different seasons).

That means that on MyAnimeList you have 2 releases:

* Senran Kagura: Ninja Flash https://myanimelist.net/anime/15119
* Senran Kagura: Shinovi Master https://myanimelist.net/anime/36037

However, on TheTVDB the Series is the same:

* https://thetvdb.com/series/senran-kagura with ID 264053

So the mapping is correct because this anime-list does not differentiate between seasons, just overall releases.

> I tried to move the media to "Season 2" folder to see if it will take the meta of season 2

The MyAnimeList metadata Agent does not provide this functionality because of the above-mentioned design. It expects your files to be organized according to how MyAnimeList has its releases organized. That means: 

* Season 1 = Senran Kagura [mal-15119]
* Season 2 = Senran Kagura Shinovi Master Tokyo Youma-hen [mal-36037]

> Is there a way for me to pick anidb or anilist for the metadata?

No. You should look into HAMA if you want Anidb or the ability to have a seasonal file/folder structure, but this will also exclude you from getting MyAnimeList Metadata.

I will close this because this isn't related to this project.
