### ISSUE TITLE
Incorrect Mappings

### ISSUE THREAD

**Issue by ScottDennison** [Fribb/anime-lists#2]
MAL entry: https://myanimelist.net/anime/38816/Hello_World
Current TheMovieDB link: https://www.themoviedb.org/movie/351430-scandal-documentary-film-hello-world
Correct TheMovieDB link: https://www.themoviedb.org/movie/604605-hello-world

---

MAL entry: https://myanimelist.net/anime/39584/Human_Lost__Ningen_Shikkaku
Current TheMovieDB link: https://www.themoviedb.org/movie/567591
Correct TheMovieDB link: https://www.themoviedb.org/movie/593240-human-lost

---

MAL entry: https://myanimelist.net/anime/35848/Promare
Current TVDB Id: 331205 (does not exist)
Correct TVDB Id: 101817
Current TheMovieDB link: (none)
Correct TheMovieDB link: https://www.themoviedb.org/movie/553600-promare

---

MAL entry: https://myanimelist.net/anime/40597/Sol_Levante
No current link
Correct TheMovieDB link: https://www.themoviedb.org/movie/688900-sol-levante

---

MAL entry: https://myanimelist.net/anime/33354/Cardcaptor_Sakura__Clear_Card-hen
Current TVDB Id: 344218 (does not exist)
Correct TVDB Id: 70668 (clear card has the same id as the original cardcaptor sakura)

**Comment by ScottDennison** [comment]
Thanks for the quick fix :)
I'm just crawling through the logs of the myanimelist agent to see any other problems, so there will probably be more incorrect/non-existant mappings coming. Do you want those in a new issue or put here?

**Comment by Fribb** [comment]
My Initial thought was that any corrections should have its own new issue. That would make it easier to follow which ones are finished and which are not. I was a bit confused when GitHub suddenly updated this ticket when you added the last mismatch while I was close to committing the changes.

On the other hand, you could also just fork the project and add the corrections to the "corrections" file (since everything else is automatically corrected), then we can merge it. You could even run the JQ commands as well to update the corrected file so that the delivery to my server and distribution to the Agents would be faster.

**Comment by ScottDennison** [comment]
I'll do a fork and pull-request. I will hopefully have it ready in an hour or so.

**Comment by Fribb** [comment]
the full list will be pulled daily at 1:00 European Central Time so no panic.

**Comment by ScottDennison** [comment]
It took a while longer than I thought, but I've identified (at least of those that in my plex library)
Corrections should obviously go in the corrections file. However should new entries go there too or go in the relevant file in the anime-mapping folder?

**Comment by Fribb** [comment]
The Mapping folders are automatically generated so anything that is changed there could be overwritten with the next time is is run.

So anything that needs correction should go in the corrections file even those who are not available yet.

**Comment by ScottDennison** [comment]
> the full list will be pulled daily at 1:00 European Central Time so no panic.

I've noticed that https://atarashii.fribbtastic.net/mapping/animeMapping_full.json still has the mappings from prior to this and #3 , could the daily pull be non-functional?

**Comment by Fribb** [comment]
That should all work automatically. The server should pull the latest version from github each day.

I will have to look into that when I'm back home

**Comment by Fribb** [comment]
I checked the file and it wasn't updated since Nov 2019 for some reason, checking the cronjob turned up that the cronjob wasn't even listed anymore so the file wasn't pulled at all.

I corrected that and created the Cronjob again, the file should now be updated with the latest version and be updated daily.
