### ISSUE TITLE
a question please

### ISSUE THREAD

**Issue by hcgiub001** [Fribb/anime-lists#20]
Hey Fribb, sorry if It's not the place to ask.

I use kodi and an addon called Fenlight. It uses TMDB database to get it's data.
TMDB doesn't have an anime section like popular anime etc
Right now getting information from MAL or other anime database means the Dev has to search for each anime to get the list of anime from TMDB.
I was wondering if your api (anime-lists) is somehow able to feed in all the anime from say a page on MAL and give out a list of all TMDB id's for the anime on that list to feed into TMDB api?
if that is so then this would be great for anime lovers on kodi. 
If I wasn't clear and you like more clarification I'll be happy to provide.
If It's not the right place to ask please delete thankyou

**Comment by Fribb** [comment]
> I was wondering if your api (anime-lists) is somehow able to feed in all the anime from say a page on MAL and give out a list of all TMDB id's for the anime on that list to feed into TMDB API?

Just for Clarification here, this project isn't really an API in which you can filter things, while it is in a JSON format (that many APIs are using) it is merely a Mapping file between related IDs.

But so that I understand it correctly, you want to be able to select certain pages like the TOP Anime or the Anime for a Season which then returns only the list of TMDB IDs, correct?

This goes well beyond the scope of what the project is meant to do.

The first thing is that this Project doesn't even come close to any request or "parsing" on the MyAnimeList Website. It is only to aggregate the already existing data from the original anime-lists project and the provided XML files there and the Anime-Offline-Database to have a comprehensive list of Mappings between the Anime Websites, so that you can hit up one list with a certain ID from a Website and then search for that ID in the list and get all related (or the one that you want) IDs.

Yes, this is different to "Here is a list of that specific thing that you want", but that was never the purpose of this project. And doing that in this project would mean that I would open this up for requests on other websites to do a similar thing.

Still, I am not quite sure why this has to be done through this project and why this couldn't be handled through the Kodi Plugin or anything in that regard. Getting what you want would be straightforward and also be much more specific realizing that in Kodi itself than doing it here.

For example, let's say you want to have the Top Anime list from MAL with the TMDB IDs instead of the MAL ID. You would hit up the [Top Anime Jikan API Endpoint](https://docs.api.jikan.moe/#tag/top/operation/getTopAnime) and get every mal_id from that list. Then you look that ID up in the anime-lists and get the TMDB ID if available. Done.

This would get even worse if you want a "season" as a separate mapping file because this would require that I parse every single season separately and store it. And, as I said above, this could potentially open up the project to requests to do the same for other websites.

All of that isn't impossible but blows the scope of this project wide open. If you really want to have this in this format, as dedicated files, I would see this as a dedicated Project in which those lists are generated based on what I outlined roughly above but then only for MAL. But this should be something that can be handled on the client side without much effort.

**Comment by hcgiub001** [comment]
Thanks for the detailed response. I'm still new and learning and found out SIMKL is what I was after, it returns TMDB id's too, so I can use their lists. Appreciate your detailed reply.
