### ISSUE TITLE
Question: How are these generated?

### ISSUE THREAD

**Issue by skarekrow** [Fribb/anime-lists#5]
Hey there! 

Great work here, just wondering how these are generated? Was looking to do something similar myself for Anilist, but wasn't sure how you even got this going.

Thanks!

**Comment by Fribb** [comment]
You can look at the Project [here](https://github.com/Fribb/MyAnimelistTitleListMapping) on how that looks in Java code.

In principle, it starts with a number, the MyAnimeList ID, which is used to request the information from MyAnimeList. The Mapping project then extracts the different titles for the Main Title as well as the Japanese and English titles and Synonyms. I also save the type so if it is a Movie or a TV-Show so that the requests can be reduced since I don't need to request something that is an Audio track or something like that.

Those titles are then each checked against the TheTVDB or TheMovieDB APIs to get a response and the Program then checks which ID has the most occurrences from the individual title requests and uses that as ID. the titles are saved in the titleMapping files and the mapping between MyAnimeList and TheTVDB or TheMovieDB are saved in the animeMapping files.
