### ISSUE TITLE
mapping fix

### ISSUE THREAD

**Issue by meisnate12** [Fribb/anime-lists#9]
{
    "thetvdb_id": 81649,
    "mal_id": 112
  },
should be 
  {
    "themoviedb_id": 129,
    "mal_id": 112
  },

**Comment by Fribb** [comment]
Your mapping seems to be wrong here.

Mal ID [112](https://myanimelist.net/anime/112) is `Chou Henshin Cosprayers` or `The Cosmopolitan Prayers` which is thetvdb_id [81649](https://www.thetvdb.com/series/cosprayers) so the mapping there is correct. It is also a TV-Show so the themoviedb_id 129 leads to [this](https://www.themoviedb.org/tv/129) which is wrong. Even looking on the Movie side, it ends up with Spirited Away instead of anything related to the mal_id.

Please check that.

**Comment by meisnate12** [comment]
this one is my bad spirited away was mapped in my library wrong and i never actually checked the id just what was attached to it
